import type { NextPage } from 'next'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Creat Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="../public/next.svg" />
      </Head>

      <main>
        <h1>Welcome to <a href="https:nextjs.org"> Next.js!</a></h1>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facere qui consectetur, ex quae eius sunt nesciunt. Perferendis fugit voluptatem porro nihil similique illum officiis velit?</p>
      </main>

    </>
  )
}
